# Generated by Django 3.2 on 2021-04-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_collection', '0002_video_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
    ]
