# Generated by Django 3.2 on 2021-04-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_collection', '0003_remove_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=2, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
